### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by tin2tin** [OllyFunkster/bangingcuts#1]
Have you considered an option to cut silence too? It also seems to be a popular feature(several projects on GitHub for that(but not for Blender).

In the read-me, maybe you could describe how you use this during recording? Do you use it to mark selections?

**Comment by OllyFunkster** [comment]
You mean cut out all parts where the audio is below the threshold? That sounds feasible, it almost does that now but currently you would end up with multiple smaller clips while above threshold. I'll think about how to best roll that in.

I'll add a demo video to the readme in the next week or so.

**Comment by tin2tin** [comment]
Great video. Now I understand what you're using your add-on for.
As for cutting the parts without sound, it is actually the same as keeping the parts with sound. :-) 

Here's an example of a very complicated project which does that, but it's not for Blender: 
https://github.com/jappeace/cut-the-crap

**Comment by OllyFunkster** [comment]
At the moment it would remove the silence, but you would only get a fixed amount of the above-threshold part rather than the whole thing as is probably desired.

It shouldn't be a massive change to add a "remove silence" specific mode, though.

**Comment by smcnally** [comment]
Using @tin2tin's fork took a Zoom recording from 57:33 to 44:58. **Banged 1497 Cuts!** in <10 minutes. No issues here, just thanks. 

In **Operation Mode** *Remove Silence*, I changed **Preroll frames** from 1 to 5. All others were the defaults. The dead air and most filler words were gone with the first pass. The Meetup presentation is now much tighter without unnatural loss afaict. 

The counter on the mouse pointer is good feedback. I'd like to see that feedback elsewhere along with total Bang time (*Total Time To Banged*?)

I didn't see it using much of the available RAM or cores, but still made quick work of it. Many thanks. 


Blender 3.6, Ubuntu Studio 22.04
The Zoom meeting recording was MP4. 
```
Major Brand                     : MP4 v2 [ISO 14496-14]
Handler Description             : H.264/AVC video
Audio Format                    : mp4a
```
